# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1

script:
  - rm -rf ./AppDir || true
  - export DESTDIR=$PWD/AppDir
  - scripts/install-build-deps.sh
  - mkdir -p build
  - cd build
  - ../scripts/deploy-mauiman.sh
  - ../scripts/deploy-mauikit.sh
  - ../scripts/deploy-mauikit-filebrowsing.sh
  - ../scripts/deploy-mauikit-texteditor.sh
  - ../scripts/deploy-mauikit-terminal.sh
  - ../scripts/deploy-bonsai.sh

AppDir:
  path: ./AppDir
  app_info:
    id: bonsai
    name: Bonsai
    icon: bonsai
    version: git
    exec: usr/bin/bonsai
    exec_args: $@
  runtime:
    env:
      PATH: '${APPDIR}/usr/bin:${APPDIR}/bin:${APPDIR}/usr/lib/x86_64-linux-gnu/libexec/kf5:${PATH}'
      # APPDIR_LIBRARY_PATH: "$APPDIR/lib/x86_64-linux-gnu:$APPDIR/usr/lib:$APPDIR/usr/lib/x86_64-linux-gnu"
      QT_QUICK_CONTROLS_STYLE: "maui-style"
  after_bundle:
    - cd $APPDIR/bin/ && ln -sf bash sh && cd -
  apt:
    arch:
    - amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
      key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3B4FE6ACC0B21F32'
    - sourceline: deb https://packagecloud.io/nitrux/depot/debian/ trixie main
      key_url: 'https://packagecloud.io/nitrux/depot/gpgkey'
    - sourceline: deb https://packagecloud.io/nitrux/testing/debian/ trixie main
      key_url: 'https://packagecloud.io/nitrux/testing/gpgkey'

    include:
    # CORE DEPENDENCIES
    - bash

    # TARGET DEPENDENCIES
    # ⚠ WARNING: DO NOT ADD libc6 AND libstdc++6 TO THIS LIST!
    - libgit2-1.7
    - libicu74

    # KF5 DEPENDENCIES
    - libkf5coreaddons5
    - libkf5i18n5
    - libkf5widgetsaddons5
    - libkf5windowsystem5
    - libkf5xmlgui5
    - libkf5iconthemes5
    - libkf5itemmodels5
    - libkf5jobwidgets5
    - libkf5kiocore5

    # QT5 DEPENDENCIES
    - libqt5core5a
    - libqt5gui5
    - libqt5qml5
    - libqt5quick5
    - libqt5sql5
    - libqt5widgets5
    - libqt5waylandclient5

    # QML DEPENDENCIES
    - qml-module-org-kde-kirigami2
    - qml-module-qtquick-controls2
    - qml-module-qtquick-shapes
    - qml-module-qt-labs-settings
    - qml-module-qtgraphicaleffects
    - qml-module-org-kde-sonnet

    exclude:
    - dbus
    - dbus-bin
    - dbus-daemon
    - dbus-session-bus-common
    - dbus-system-bus-common
    - dirmngr
    - fdisk
    - fontconfig
    - fontconfig-config
    - fonts-dejavu-core
    - fonts-dejavu-mono
    - gcc-14-base
    - gnupg
    - gnupg-utils
    - gpg
    - gpg-agent
    - gpgconf
    - gpgsm
    - gpgv
    - kded5
    - keyboxd
    - kio
    - kpackagetool5
    - libacl1
    - libapparmor1
    - libargon2-1
    - libasound2
    - libasound2-data
    - libassuan0
    - libaudit-common
    - libaudit1
    - libblkid1
    - libbrotli1
    - libbsd0
    - libbz2-1.0
    - libc6
    - libcanberra0
    - libcap-ng0
    - libcap2
    - libcap2-bin
    - libcom-err2
    - libcrypt1
    - libcryptsetup12
    - libdb5.3
    - libdbus-1-3
    - libdbusmenu-qt5-2
    - libdevmapper1.02.1
    - libdouble-conversion3
    - libepoxy0
    - libevdev2
    - libexpat1
    - libfdisk1
    - libffi8
    - libfontconfig1
    - libfreetype6
    - libgcc-s1
    - libgcrypt20
    - libgdbm-compat4
    - libgdbm6
    - libglib2.0-0
    - libgmp10
    - libgnutls30
    - libgomp1
    - libgpg-error0
    - libgpgme11
    - libgpgmepp6
    - libgraphite2-3
    - libgssapi-krb5-2
    - libgudev-1.0-0
    - libharfbuzz0b
    - libhogweed6
    - libhttp-parser2.9
    - libice6
    - libicu74
    - libidn2-0
    - libimobiledevice6
    - libinput-bin
    - libinput10
    - libjpeg-turbo8
    - libjpeg8
    - libjson-c5
    - libk5crypto3
    - libkeyutils1
    - libkf5archive-data
    - libkf5archive5
    - libkf5auth-data
    - libkf5authcore5
    - libkf5codecs-data
    - libkf5codecs5
    - libkf5completion-data
    - libkf5completion5
    - libkf5config-data
    - libkf5configcore5
    - libkf5configgui5
    - libkf5configwidgets-data
    - libkf5configwidgets5
    - libkf5coreaddons-data
    - libkf5crash5
    - libkf5dbusaddons-data
    - libkf5dbusaddons5
    - libkf5declarative-data
    - libkf5declarative5
    - libkf5doctools5
    - libkf5guiaddons-bin
    - libkf5guiaddons-data
    - libkf5guiaddons5
    - libkf5i18n-data
    - libkf5iconthemes-data
    - libkf5iconthemes5
    - libkf5itemviews-data
    - libkf5itemviews5
    - libkf5jobwidgets-data
    - libkf5jobwidgets5
    - libkf5kiocore5
    - libkf5kiogui5
    - libkf5kiontlm5
    - libkf5kiowidgets5
    - libkf5kirigami2-5
    - libkf5notifications-data
    - libkf5notifications5
    - libkf5package-data
    - libkf5package5
    - libkf5quickaddons5
    - libkf5service-bin
    - libkf5service-data
    - libkf5service5
    - libkf5solid5
    - libkf5solid5-data
    - libkf5sonnet5-data
    - libkf5sonnetcore5
    - libkf5sonnetui5
    - libkf5textwidgets-data
    - libkf5textwidgets5
    - libkf5wallet-bin
    - libkf5wallet-data
    - libkf5wallet5
    - libkf5widgetsaddons-data
    - libkf5widgetsaddons5
    - libkf5windowsystem-data
    - libkf5windowsystem5
    - libkmod2
    - libkrb5-3
    - libkrb5support0
    - libksba8
    - libkwalletbackend5-5
    - libldap2
    - libltdl7
    - liblz4-1
    - liblzma5
    - libmd0
    - libmd4c0
    - libmount1
    - libmtdev1
    - libncursesw6
    - libnettle8
    - libnpth0
    - libogg0
    - libp11-kit0
    - libpam-modules
    - libpam-modules-bin
    - libpam-runtime
    - libpam-systemd
    - libpam0g
    - libpcre2-16-0
    - libpcre2-8-0
    - libperl5.38
    - libplist3
    - libpng16-16
    - libpolkit-agent-1-0
    - libpolkit-gobject-1-0
    - libpolkit-qt5-1-1
    - libqca-qt5-2
    - libqt5dbus5
    - libqt5network5
    - libqt5qmlmodels5
    - libqt5qmlworkerscript5
    - libqt5quickcontrols2-5
    - libqt5quickshapes5
    - libqt5quicktemplates2-5
    - libqt5svg5
    - libqt5texttospeech5
    - libqt5waylandclient5
    - libqt5x11extras5
    - libqt5xml5
    - libreadline8
    - libsasl2-2
    - libsasl2-modules-db
    - libseccomp2
    - libselinux1
    - libsm6
    - libsmartcols1
    - libsqlite3-0
    - libssh2-1
    - libssl3
    - libstdc++6
    - libsystemd-shared
    - libsystemd0
    - libtasn1-6
    - libtdb1
    - libtinfo6
    - libudev1
    - libunistring5
    - libusbmuxd6
    - libuuid1
    - libvorbis0a
    - libvorbisfile3
    - libwacom-common
    - libwacom9
    - libxau6
    - libxcb-dri2-0
    - libxcb-dri3-0
    - libxcb-glx0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-present0
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-render0
    - libxcb-res0
    - libxcb-shape0
    - libxcb-shm0
    - libxcb-sync1
    - libxcb-util1
    - libxcb-xfixes0
    - libxcb-xinerama0
    - libxcb-xinput0
    - libxcb-xkb1
    - libxcb1
    - libxdmcp6
    - libxfixes3
    - libxkbcommon-x11-0
    - libxkbcommon0
    - libxml2
    - libxrender1
    - libxslt1.1
    - libzstd1
    - mount
    - perl
    - perl-base
    - perl-modules-5.38
    - pinentry-curses
    - qml-module-org-kde-kquickcontrolsaddons
    - qml-module-qtgraphicaleffects
    - qml-module-qtqml-models2
    - qml-module-qtquick-layouts
    - qml-module-qtquick-templates2
    - qml-module-qtquick-window2
    - qml-module-qtquick2
    - readline-common
    - sound-theme-freedesktop
    - systemd
    - systemd-dev
    - systemd-sysv
    - util-linux
    - xkb-data
    - zlib1g

  files:
    include:
    - /usr/bin/which
    exclude:
    - usr/include
    - usr/share/man
    - usr/share/doc
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
    - lib/systemd
    - etc/systemd
    - usr/lib/systemd
    - usr/bin/systemd*
    - usr/bin/dpkg*
    - usr/bin/*-linux-gnu-*
    - usr/share/locale

AppImage:
  arch: x86_64
  comp: xz
  file_name: bonsai-git-x86_64.AppImage
  update-information: gh-releases-zsync|Nitrux|bonsai|git|*x86_64.AppImage.zsync